// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hukwuyhyqnetqwggsqno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1a3d1eWh5cW5ldHF3Z2dzcW5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjQ2NTEsImV4cCI6MjA3MDc0MDY1MX0.Te80IzAGYHhD9p-thzhyAWmfT4OSaT6AUf27_coFjXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});